before_script:
  - docker version
  - apt-get install docker-compose
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up tester-image
