before_script:
  - docker version
  - ls

stages:
  - test
  - deploy

test-stage:
  stage: test
  script:
    - docker build -f Dockerfile_Test .

deploy-stage:
  stage: deploy
  script:
    - docker compose down &
    - docker compose build &
    - docker compose up &
