before_script:
  - docker version
  - ls
  - lsb_release -d
  - sudo apt update
  - sudo apt install docker-compose
  - docker-compose version

stages:
  - test

test-stage:
  stage: test
  script:
    - docker build -f Dockerfile_Test .

