version: "2.0"
services:
    db:
        restart: always
        image: "mcr.microsoft.com/mssql/server:latest:ubicomp"
        ports:
            - "1433:1433"
        volumes:
            - C:\Users\Cliente\Documents\SqlServer\SqlServerData:/var/opt/mssql/data
            - C:\Users\Cliente\Documents\SqlServer\SqlServerLog:/var/opt/mssql/log
            - C:\Users\Cliente\Documents\SqlServer\SqlServerSecrets:/var/opt/mssql/secrets
        environment:
            SA_PASSWORD: "PASSWORDteste2022.!?"
            ACCEPT_EULA: "Y"
    mosquitto:
        restart: always
        image: eclipse-mosquitto:ubicomp
        ports:
            - "8889:1883"
        volumes:
            - C:\Users\Cliente\Documents\mosquittoConfig:/mosquitto/config
    web:
        restart: always
        build: .:ubicomp
        ports:
            - "8888:80"
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
        depends_on:
            - db
            - mosquitto
         
